name: Create Beta Tag

on:
  push:
    branches: [ beta ]
    paths:
      - "module.json"

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version
        id: read
        run: |
          VERSION=$(jq -r '.version' module.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git fetch --tags

      - name: Tag if new
        run: |
          TAG="v${{ steps.read.outputs.version }}"
          [[ "$TAG" =~ -beta$ ]] || TAG="${TAG}-beta"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists; skipping."
            exit 0
          fi
          echo "🚀 Creating new beta tag: $TAG"
          git tag -a "$TAG" -m "Pre-release $TAG"
          git push origin "$TAG"
