name: Publish Beta Pre-release

on:
  push:
    tags:
      - "v*-beta"

permissions:
  contents: write

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine tag and version
        id: read
        run: |
          TAG="${GITHUB_REF##*/}"
          VERSION="${TAG#v}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Publishing pre-release for $TAG"

      - name: Build module ZIP
        id: build
        run: |
          NAME="Runes-and-Remnants-${{ steps.read.outputs.tag }}.zip"
          zip -r "$NAME" . \
            -x ".git/*" ".github/*" "node_modules/*" "tests/*" "scripts/*" \
               "*.psd" "*.ai" "*.blend" ".DS_Store" "README*.md"
          echo "zip_name=$NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.read.outputs.tag }}
          name: "Runes & Remnants ${{ steps.read.outputs.tag }}"
          prerelease: true
          generate_release_notes: true
          files: |
            ${{ steps.build.outputs.zip_name }}
            module.json
