name: Block Non-Beta Merges to Main

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  restrict:
    runs-on: ubuntu-latest
    steps:
      - name: Reject PRs not from beta
        if: github.head_ref != 'beta'
        run: |
          echo "❌ Only PRs from 'beta' may be merged into 'main'."
          exit 1
