name: Block merges not from dev

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR source branch is dev
        if: github.head_ref != 'dev'
        run: |
          echo "❌ Only PRs from 'dev' can be merged into 'main'."
          echo "You tried to merge from '${{ github.head_ref }}'."
          exit 1
