name: Lint

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Only install if a lockfile exists (npm ci requires it)
      - name: Install deps (if any)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            echo "No package-lock.json found; skipping npm install."
          else
            echo "No package.json; skipping install."
          fi

      # Run ESLint only if it's present
      - name: ESLint (if configured)
        run: |
          if [ -f node_modules/.bin/eslint ]; then
            npx eslint .
          else
            echo "No ESLint configured, skipping."
          fi