name: Lint

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          else
            echo "⚠️ No package.json found; skipping dependency install."
          fi

      - name: Run ESLint (if configured)
        run: |
          if [ -f node_modules/.bin/eslint ]; then
            echo "🔍 Running ESLint..."
            npx eslint . --max-warnings=0
          else
            echo "⚠️ ESLint not configured; skipping lint."
          fi
