name: Prepare Beta Release PR

on:
  push:
    branches: [ beta ]
    paths:
      - "module.json"

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read module.json
        id: read
        run: |
          VERSION=$(jq -r '.version' module.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update download URL
        run: |
          VERSION="${{ steps.read.outputs.version }}"
          URL="https://github.com/${{ github.repository }}/releases/download/v${VERSION}/Runes-and-Remnants-v${VERSION}.zip"
          jq --arg url "$URL" '.download = $url' module.json > module.tmp && mv module.tmp module.json

      - name: Create PR to main
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: prepare v${{ steps.read.outputs.version }} release"
          title: "Release v${{ steps.read.outputs.version }}"
          body: |
            Automated beta release PR.
          branch: "release/v${{ steps.read.outputs.version }}"
          base: "main"
