name: Prepare Beta Release
on:
  push:
    branches: [ beta ]
    paths:
      - "module.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  beta-release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version
        id: version
        run: echo "VERSION=$(jq -r '.version' module.json)" >> $GITHUB_OUTPUT

      - name: Build beta zip
        run: |
          NAME="Runes-and-Remnants-v${{ steps.version.outputs.VERSION }}.zip"
          zip -r "$NAME" . \
            -x ".git/*" ".github/*" "node_modules/*" "tests/*"
          echo "ZIP=$NAME" >> $GITHUB_OUTPUT

      - name: Create Beta Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: "Runes & Remnants v${{ steps.version.outputs.VERSION }} (Beta)"
          prerelease: true
          generate_release_notes: true
          files: |
            ${{ steps.version.outputs.ZIP }}
            module.json
