name: Validate module.json

on:
  pull_request:
  push:
    branches: [ beta ]
    paths:
      - "module.json"
      - ".github/workflows/validate-module-json.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure valid JSON
        run: |
          jq . module.json >/dev/null

      - name: Basic field checks
        run: |
          ID=$(jq -r '.id' module.json)
          VER=$(jq -r '.version' module.json)
          ES=$(jq -r '.esmodules[0]' module.json)
          if [ -z "$ID" ] || [ "$ID" = "null" ]; then echo "Missing id"; exit 1; fi
          if [ -z "$VER" ] || [ "$VER" = "null" ]; then echo "Missing version"; exit 1; fi
          if [ -z "$ES" ] || [ "$ES" = "null" ]; then echo "Missing esmodules[0]"; exit 1; fi
          echo "module.json looks sane ✅"
